# Generated by Django 3.0.8 on 2020-09-07 15:55

from django.db import migrations
from django.core.management import call_command


class Migration(migrations.Migration):

    def initial_data(apps, schema_editor):
        call_command("loaddata", "initial_data.json")

    dependencies = [
        ('fortytwoapps', '0005_contact_photo'),
    ]

    operations = [
        migrations.RunPython(initial_data),
    ]
