# Generated by Django 3.0.8 on 2020-09-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortytwoapps', '0002_auto_20200907_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='time',
            new_name='timestamp',
        ),
    ]
