# Generated by Django 3.0.8 on 2020-09-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortytwoapps', '0003_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='url',
            new_name='path',
        ),
    ]
