# Generated by Django 3.0.8 on 2020-09-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortytwoapps', '0004_auto_20200921_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=100)),
                ('objectname', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
